parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''
    invoice_header_path: ''
    invoice_footer_path: ''
    company: ''
    stripe_api_key: pk_test_bhDUFrkPtZzTgt3U651iM4Pg
    stripe_api_secret: sk_test_MLOl7aa6O5rfEQ0RChy7Rkoc
    webPath: '%env(resolve:webPath)%'
doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.5'
#        charset: utf8mb4
        charset: UTF8

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'
    orm:
#        auto_generate_proxy_classes: '%kernel.debug%'
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            numeric_functions:
                power: App\DQL\PowerFunction
                cos: App\DQL\CosFunction
                multiply: App\DQL\MultiplyFunction
                divide: App\DQL\DivideFunction
            datetime_functions:
                date: App\DQL\DateFunction
                MONTH: App\DQL\MonthFunction
                YEAR: App\DQL\YearFunction
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/'
                prefix: 'App\Entity'
                alias: App