
wsb:
    resource: "@App/Resources/config/WsbBundle/routing.yml"
    prefix:   /
base_url:
    path:      /
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin